# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CatalogImporter < Formula
  desc "Official incident.io catalog importer, for syncing catalog entries."
  homepage "https://incident.io/"
  version "2.6.0"

  on_macos do
    on_intel do
      url "https://github.com/incident-io/catalog-importer/releases/download/v2.6.0/catalog-importer_2.6.0_darwin_amd64.tar.gz"
      sha256 "c13f6a438efd91db4b02346cad269a8bcd594393dec3a5589abec2db3ab34bdd"

      def install
        bin.install "catalog-importer"
      end
    end
    on_arm do
      url "https://github.com/incident-io/catalog-importer/releases/download/v2.6.0/catalog-importer_2.6.0_darwin_arm64.tar.gz"
      sha256 "a969d6eb2cfa4b8325b9c68026a5add5dbd8b781e821cde00776e2092bb02148"

      def install
        bin.install "catalog-importer"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/incident-io/catalog-importer/releases/download/v2.6.0/catalog-importer_2.6.0_linux_amd64.tar.gz"
        sha256 "33e03ad314f9f04caa23a0847d7b477c90b7e28acbc33ec18b865a1f5ad707d2"

        def install
          bin.install "catalog-importer"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/incident-io/catalog-importer/releases/download/v2.6.0/catalog-importer_2.6.0_linux_arm64.tar.gz"
        sha256 "14bbda6823724575b043f9e0f56247a4d96ee4c5296bc23eb05d57dd5e60eec2"

        def install
          bin.install "catalog-importer"
        end
      end
    end
  end
end
