# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inc < Formula
  desc "CLI for incident.io"
  homepage "https://incident.io/"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/inc/releases/download/v0.4.1/inc_0.4.1_darwin_amd64.tar.gz"
      sha256 "8c0b72b3b7a52fd615936b41220a4ad379769e9add0789a78568545ca125a0ad"

      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incident-io/inc/releases/download/v0.4.1/inc_0.4.1_darwin_arm64.tar.gz"
      sha256 "4d8826f4713880d0bc069ffd5b209c98e65d142848347872ed7b243482001d77"

      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/inc/releases/download/v0.4.1/inc_0.4.1_linux_amd64.tar.gz"
      sha256 "7f3c49e6aa93d2e9b75162d1db8045bd1729bada31be888cc2ae9c2c74851c20"
      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/inc/releases/download/v0.4.1/inc_0.4.1_linux_arm64.tar.gz"
      sha256 "17b0cc76ad4500e80c2aa340e6b645cf2a612debf919dcf60e85fe27865550fa"
      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
  end
end
