# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inc < Formula
  desc "CLI for incident.io"
  homepage "https://incident.io/"
  version "0.4.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/inc/releases/download/v0.4.23/inc_0.4.23_darwin_amd64.tar.gz"
      sha256 "f1e75fdee2e859926f3fb4b220c60ec5b318310e242747e2568f7e4a378f0b27"

      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incident-io/inc/releases/download/v0.4.23/inc_0.4.23_darwin_arm64.tar.gz"
      sha256 "171bce001ca82fde3ba83beedf3cd2cd3fec7c81c92c72aaec829267ccd06512"

      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/inc/releases/download/v0.4.23/inc_0.4.23_linux_amd64.tar.gz"
      sha256 "fdb4a03ea7347dcdb62b7c4336fbdb45938d28a71bea9e08921c04c415cca8b6"
      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/inc/releases/download/v0.4.23/inc_0.4.23_linux_arm64.tar.gz"
      sha256 "7ded91a2c63c8b6f03e83edb1f71521b291839438e91ce8648fc3d233c791b1b"
      def install
        bin.install "inc"
        bash_completion.install "completions/inc.bash" => "inc"
        zsh_completion.install "completions/inc.zsh" => "_inc"
        fish_completion.install "completions/inc.fish"
      end
    end
  end
end
