# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IncidentTap < Formula
  desc "Official incident.io Singer tap, for extracting data into Singer targets."
  homepage "https://incident.io/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.2.0/incident-tap_0.2.0_darwin_amd64.tar.gz"
      sha256 "88b7ccd8e519508bff18c6e27acc64b8c8b052128e065ab6505f27c691b86bb3"

      def install
        bin.install "incident-tap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.2.0/incident-tap_0.2.0_darwin_arm64.tar.gz"
      sha256 "788e6a4f7d2615f221e60705637855c27d9cd97de0c3c6fa97f80b8b548e9a05"

      def install
        bin.install "incident-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.2.0/incident-tap_0.2.0_linux_arm64.tar.gz"
      sha256 "734de1da66ea4410d28277fdbe40f1ee661ef26919a2487e3a85ca5ee0f237fc"

      def install
        bin.install "incident-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.2.0/incident-tap_0.2.0_linux_amd64.tar.gz"
      sha256 "93e15e0a1e23d350bba7d6d1a26ea8ddd07d04c54b6e0d16577c2924c357212b"

      def install
        bin.install "incident-tap"
      end
    end
  end
end
