# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TapIncident < Formula
  desc "Official incident.io Singer tap, for extracting data into Singer targets."
  homepage "https://incident.io/"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.4.0/tap-incident_0.4.0_darwin_amd64.tar.gz"
      sha256 "ca470414f095d87d71c77abfbb53d1b410ff3d4f65f9b19ebf19a5173e4fc8b8"

      def install
        bin.install "tap-incident"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.4.0/tap-incident_0.4.0_darwin_arm64.tar.gz"
      sha256 "d716ca128d8fcabe271eaa52e14ebda4bd116785e429f8763357aec75b2f21b6"

      def install
        bin.install "tap-incident"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.4.0/tap-incident_0.4.0_linux_arm64.tar.gz"
      sha256 "702298035b502b6ce815731a2745e049ce887282b7f2bbe4a2e7846c39a270f2"

      def install
        bin.install "tap-incident"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.4.0/tap-incident_0.4.0_linux_amd64.tar.gz"
      sha256 "5ebdb27b980d5e390fd1135b6b6b67f8817f5cf27fcb02a8d0efce18f803a5ba"

      def install
        bin.install "tap-incident"
      end
    end
  end
end
