# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TapIncident < Formula
  desc "Official incident.io Singer tap, for extracting data into Singer targets."
  homepage "https://incident.io/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.3.0/tap-incident_0.3.0_darwin_arm64.tar.gz"
      sha256 "1f5793e9d6f6f95a9b7daaa277faf25b7e26ce7b14edd40919b1e01a1b722fe8"

      def install
        bin.install "tap-incident"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.3.0/tap-incident_0.3.0_darwin_amd64.tar.gz"
      sha256 "2d012342dedab9d35c716bde1af8802f3e25b3d79149b8023a767df7f488d9aa"

      def install
        bin.install "tap-incident"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.3.0/tap-incident_0.3.0_linux_arm64.tar.gz"
      sha256 "0eadcf76011f8785f53a132fac7d6b95ad376d61df5b335a32cbbd5b938131c2"

      def install
        bin.install "tap-incident"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/incident-io/singer-tap/releases/download/v0.3.0/tap-incident_0.3.0_linux_amd64.tar.gz"
      sha256 "30d4e52e1b9043bad836ef2dc2e5b002bd10d11a8366407b973e26434a7b9ce5"

      def install
        bin.install "tap-incident"
      end
    end
  end
end
